NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('news_id/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('add/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe')
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    authorRating = models.IntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum("rating"))
        pRat = 0
        pRat += postRat.get("postRating")

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum("rating"))
        cRat = 0
        cRat += commentRat.get("commentRating")

        self.authorRating = pRat*3 + cRat
        self.save()

    def __str__(self):
        return self.authorUser.username


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    ARTICLE = "AR"
    NEWS = "NW"
    CATEGORY_CHOICES = (
        (ARTICLE, "Статья"),
        (NEWS, "Новость")
    )
    #INFORMATION_TECHNOLOGY = "IT"
    #SPORT = "SP"
    #CARS = "CA"
   # POLITICS = "POL"
   # FOOD_MANAGMENT = "FM"
   # CATEGORYS_CHOICES = (
    #    (INFORMATION_TECHNOLOGY, "Айти"),
    #    (SPORT, "Спорт"),
    #    (CARS, "Машины"),
      #  (POLITICS, "Политика"),
      #  (FOOD_MANAGMENT, "Управление качесвом продуктов питания")
  #  )

    categoryTypes = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    #postCategory = models.CharField(max_length=3, choices=CATEGORYS_CHOICES, default = INFORMATION_TECHNOLOGY)
    title = models.CharField(max_length=256)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:124] + "..."

    def __str__(self):
        return f'{self.categoryTypes.title()}: {self.title[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post.title} | {self.category.name}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/news/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):
    #title = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'categoryTypes',
            'author',
            'category',

        ]

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get("title")
        if description is not None and len(description) < 10:
            raise ValidationError({
                "title": "Заголовк должен быть длиннее."
            })

        return cleaned_data

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title[0].islower():
            raise ValidationError(
                "Заголовок должен начинаться с заглавной буквы"

            )

        #cleaned_data = super().clean()
        #description = cleaned_data.get("title")
       # if title == title:
            #raise ValidationError(
             #   "Такой заголовок уже используется."
           # )
        return title

NewsPaper/news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostForm
from .models import *
from .filters import PostFilter


class PostList(ListView):
    model = Post
    ordering = '-rating'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    ordering = 'name'
    template_name = 'news_id.html'
    context_object_name = 'post'


class PostCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.update_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


@login_required
def update_me(request):
    user = request.user
    premium_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
    return redirect('news/')


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.category).order_by('-dateCreation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscribers'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    message = 'Вы успешно подписались на рассылку новостей из категории'
    return render(request, 'subscribe.html', {'category': category, 'message': message})

NewsPaper/news/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1 class="text-center">Новости <span class="text-muted fs-6 fw-normal">Всего: {{ page.obj.paginator.count }}</span></h1>
    {% if is_not_subscribers %}
        <p class="text-center"><a href="{% url 'subscribe' category.id%}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
<hr>

<ul class="list-group list-group-flush">
    {% for post in category_news%}
        <li class="list-group-item">
            <small class="fw-bold">{{post.dateCreation|date:'d M Y' }}</small>
            <a href="{% url 'post_detail' post.id %}">{{ post.title }}</a>
            <small class="text-muted">(автор: {{ post.author }})</small> <br>
            <small class="fw-bold">категории:
                {% for category in post.category.all %}
                    <a href="{% url 'category_list' category.id%}">{{ category }}</a>
                {% endfor %}
            </small>
            <p>{{post.text | truncatechars:210}}</p>
        </li>
    {% endfor %}
</ul>


{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1%}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

    {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/news/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравсвуй! новые статьи за прошедшую неделю!</h2>
<ul>
  {% for post in posts %}
  <li><a href="{{ link }}{{ post.get_absolut_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

NewsPaper/news/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
   <hr>


    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}">Добавить пост</a>
    {% endif %}

   {% if news %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Дата</td>
               <td>Тематика</td>
               <td>Текст</td>


               {% if perms.news.change_post or perms.news.delete_post %}
               <td>Действия</td>
               {% endif %}
           </tr>

           {% for post in news %}
           <tr>
               <td>{{ post.title }}</td>
               <td><div align = "center">{{ post.text|truncatechars:20 }}</div></td>
               <td>{{ post.categoryTypes}}</td>
               <td>{{ post.dateCreation|date:'d M Y' }}</td>
               <td>{{ category}}
                   {% for category in post.category.all %}
                    <a href="{% url 'category_list' pk=category.id%}">{{ category }}</a>
                    {% endfor %}
               </td>
               <td>{{ post.text|censor}}</td>

               <td>
                   {% if perms.news.change_post %}
                   <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
                   <a href="{% url 'post_delete' post.id %}">Удалить</a>
                   {% endif %}

               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}

{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1%}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

    {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}Конец</a>
       {% endif %}
   {% endif %}


{% endblock content %}

NewsPaper/news/templates/news_id.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ post }}</h1>
<h1>{{post.dateCreation}}</h1>
<h1>{{post.text|censor}}</h1>
<h1>{{post.rating}}</h1>

{% endblock content %}

NewsPaper/news/templates/post_created_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в твоём любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

NewsPaper/news/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/news/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/news/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content%}
    <h1 class="text-center">{{ message }} {{ category }}!</h1>
{% endblock content%}